### ISSUE TITLE
Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by Kadantte** [felicienfrancois/node-resourcehacker#6]
```shell
C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark (master) (whatsapp-desktop-dark@0.3.4678)
λ npm install

> resourcehacker@4.2.51 postinstall C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark\node_modules\resourcehacker
> node scripts/install.js

Downloading ResourceHacker by Angus Johnson...
_http_client.js:131
  var expectedProtocol = defaultAgent.protocol;
                                      ^

TypeError: Cannot read property 'protocol' of undefined
    at new ClientRequest (_http_client.js:131:39)
    at request (http.js:44:10)
    at Object.get (http.js:48:15)
    at Object.<anonymous> (C:\Users\Candyseul\Desktop\WADark-Windows\whatsapp-desktop-dark\node_modules\resourcehacker\scripts\install.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resourcehacker@4.2.51 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the resourcehacker@4.2.51 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by felicienfrancois** [comment]
I can't reproduce here.
Can you please give me more information about your setup ?
- Version of windows
- Version of nodejs
- The shell you're using (cmd, powershell, git-bash, ...)
- Is any of the following env variables are set ? `npm_config_proxy` `http_proxy` `HTTP_PROXY`

**Comment by Kadantte** [comment]
OS: Windows 10 1903
node: 12.10.0
npm: 6.10.3
yarn: 1.17.3
Shell: cmder also I tried cmd too.
env variables: Nothing I'm not using anything.
EDIT: my last edit was a mistake from my side sorry.
EDIT2: I build the tool with Github workflows so here's what happens:
The build on node 8.x was successful but in node version 10.x and 12.x it fails.

![65404691-7a397500-ddd1-11e9-8361-c4a52d5a4377](https://user-images.githubusercontent.com/11579313/65472167-0a2afd80-de6a-11e9-896a-d0d7daf69df6.png)
